name: Release

# This workflow creates version bump pull requests when changes are pushed to main.
# It does NOT publish packages to npm automatically - publishing is disabled until MVP completion.
#
# Current behavior:
# 1. Runs quality checks (linting, type checking, tests)
# 2. Creates "Version Packages" pull requests with changelog updates
# 3. Auto-merge is handled by the dedicated auto-merge-version-pr.yml workflow
# 4. When version PR is merged, packages are versioned but NOT published
#
# To enable publishing after MVP completion:
# 1. Add NPM_TOKEN to repository secrets
# 2. Update the changesets action to include publish step
# 3. Update version-packages script to include publishing

on:
  push:
    branches:
      - main

# Workflow-level permissions
permissions:
  contents: write
  pull-requests: write
  actions: read
  checks: read

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Create Release PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: read
      checks: read
      repository-projects: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # This is important for the action to be able to create PRs
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm run build

      - name: Run linting
        run: pnpm run lint

      - name: Type check
        run: pnpm exec tsc --noEmit

      - name: Type check tests
        run: pnpm exec tsc --project tsconfig.test.json --noEmit

      - name: Run tests
        run: pnpm run test

      # Check changeset status before processing
      - name: Check for changesets
        run: |
          echo "Checking for changeset files..."
          ls -la .changeset/ | grep -E '\.(md|json)$' || echo "No changeset files found"
          echo "Changeset status:"
          pnpm changeset status

      # Create version bump PRs without publishing to npm
      # Publishing will be enabled after MVP completion
      # Auto-merge is handled by the dedicated auto-merge workflow
      - name: Create Release Pull Request or Apply Versions
        id: changesets
        uses: changesets/action@v1.5.3
        with:
          version: pnpm changeset version
          commit: "chore: version packages"
          title: "chore: version packages"
          createGithubReleases: false
          setupGitUser: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM_TOKEN not needed since we're not publishing yet
          # Will be added when ready for public releases after MVP completion

      # Log information about the changesets action results
      - name: Log Changesets Results
        run: |
          echo "Changesets action completed"
          echo "Has changesets: ${{ steps.changesets.outputs.hasChangesets }}"
          echo "Published: ${{ steps.changesets.outputs.published }}"
          if [ "${{ steps.changesets.outputs.pullRequestNumber }}" != "" ]; then
            echo "Version Packages PR created: #${{ steps.changesets.outputs.pullRequestNumber }}"
            echo "The dedicated auto-merge workflow will handle merging this PR automatically"
          else
            echo "No Version Packages PR was created (no pending changesets or already applied)"
          fi
